server:
  port: 80
spring:
  datasource:
    #mysql6以后必须driver-class-name中间加cj，url设置时区，否则会报错
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=UTC
    username: root
    password: gpj031225
reggie:
  path: E:\\reggie\\img\\
#  main:
#    banner-mode: on
    #???????
#  application:
#    name: reggie_takeout
#
#mybatis-plus:
#  configuration:
#    #????????????????????????????????????????????address_book???AddressBook
#    map-underscore-to-camel-case: true
#    #    mysql???
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      #id?????ASSIGN_ID
#      id-type: ASSIGN_ID
#    banner: false
#      ?????????????????????????????@TableName
#      table-prefix: tbl_
